version: "3.7"
services:
  nginx:
    image: nginx:1.17.3
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ".:/var/www/html/"
      - "./webserver/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - php
  php:
    build:
      context: .
    image: phpdocker
    container_name: php
    volumes:
      - ".:/var/www/html/"
    links:
      - mysql
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "33061:3306"
    volumes:
      - mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: 'db_proj'
      MYSQL_ROOT_PASSWORD: '12345'
volumes:
  mysql: