version: "3.7"
services:
  nginx:
    image: nginx:1.17.3
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ".:/var/www/html/"
      - "./webserver/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - php
  php:
    build:
      context: .
    image: phpdocker
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ".:/var/www/html/"
    links:
      - mysql
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "33061:3306"
    volumes:
      - mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: 'db_proj'
      MYSQL_ROOT_PASSWORD: '12345'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql:mysql
    ports:
      - "8001:80"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: test
volumes:
  mysql: